# Generated by Django 5.2.1 on 2025-09-06 16:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpromotionhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
