# Generated by Django 5.2.1 on 2025-06-25 22:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('PP1', 'Pre-Primary 1'), ('PP2', 'Pre-Primary 2'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('J7', 'Junior Secondary Grade 7'), ('J8', 'Junior Secondary Grade 8'), ('J9', 'Junior Secondary Grade 9')], max_length=3)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('grade_level', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3'), ('MS', 'Mid Semester'), ('ES', 'End Semester'), ('AN', 'Annual')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'start_date'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='students.class')),
            ],
            options={
                'ordering': ['class_ref', 'name'],
                'unique_together': {('name', 'class_ref', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique identifier for the student', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed')], default='U', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('date_admitted', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.stream')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Promotion', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('from_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='students.class')),
                ('from_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_stream_from', to='students.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
                ('to_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='students.class')),
                ('to_stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_stream_to', to='students.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('comment', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.exam')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.subject')),
            ],
            options={
                'verbose_name': 'Exam Score',
                'verbose_name_plural': 'Exam Scores',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_st_admissi_321db4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'subject', 'exam')},
        ),
    ]
