# Generated by Django 5.2.1 on 2025-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='legacy_admission_number',
            field=models.CharField(blank=True, help_text='Original admission number from legacy system', max_length=20, null=True, unique=True, verbose_name='Legacy Admission Number'),
        ),
    ]
