# Generated by Django 5.2.1 on 2025-06-27 09:10

from django.db import migrations


from django.db import migrations

def fix_examresult_table(apps, schema_editor):
    # This is the forward migration
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER TABLE IF EXISTS exams_examresult 
            RENAME TO students_examresult;
        """)

def reverse_fix(apps, schema_editor):
    # This is the reverse migration
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            ALTER TABLE IF EXISTS students_examresult 
            RENAME TO exams_examresult;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exampaper_examresult'),
    ]

    operations = [
        migrations.RunPython(fix_examresult_table, reverse_fix),
    ]
