# Generated by Django 5.2.1 on 2025-06-27 09:34

from django.db import migrations

def fix_table_reference(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            DROP TABLE IF EXISTS exams_examresult;
            ALTER TABLE students_examresult RENAME TO students_examresult;
        """)
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("""
            DROP TABLE IF EXISTS exams_examresult;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_examresult_student_alter_examresult_table'),
    ]

    operations = [
         migrations.RunPython(fix_table_reference),
    ]
