# Generated by Django 5.2.1 on 2025-06-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_fix_examresult_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Exam Result', 'verbose_name_plural': 'Exam Results'},
        ),
    ]
